x-base_service: &base_service
  build: ./services/comfy/
  image: fmsunyh/sd-comfy:latest

  stop_signal: SIGKILL
  tty: true

  extra_hosts:
    - "raw.githubusercontent.com:185.199.108.133"
  user: "aigc:aigc" # 容器进程以 aigc 用户身份运行

name: comfyui

services:
  flux: &automatic
    <<: *base_service
    profiles: [ "flux" ]
    container_name: comfyui-flux
    ports:
      - "${WEBUI_PORT:-62801}:7860"
    volumes:
      - &v1 ./volumes/flux/data:/data
      - &v2 /tmp/output111:/output
      # - &v3 ./volumes/flux/output:/data/output

    environment:
      - CLI_ARGS=--port 7860 --disable-cuda-malloc
    networks:
      - shared-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ compute, utility ]

  wan2.1: &automatic
    <<: *base_service
    profiles: [ "wan2.1" ]
    container_name: comfyui-wan2.1
    ports:
      - "${WEBUI_PORT:-62802}:7860"
    volumes:
      - &v1 ./volumes/wan2.1/data:/data
      - &v2 ./volumes/wan2.1/output:/output

    environment:
      - CLI_ARGS=--port 7860 --disable-cuda-malloc
    networks:
      - shared-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ compute, utility ]

  comfyui-dev: &automatic
    <<: *base_service
    profiles: [ "comfyui-dev" ]
    container_name: comfyui-dev
    ports:
      - "${WEBUI_PORT:-62803}:7860"
    volumes:
      - &v1 ./volumes/comfyui-dev/data:/data
      - &v2 ./volumes/comfyui-dev/output:/output
      - &v3 ./volumes:/volumes
      - &v4 ./volumes/comfyui-dev/data/extra_model_paths.yaml:/home/aigc/app/extra_model_paths.yaml

    environment:
      - CLI_ARGS=--port 7860 --disable-cuda-malloc
    networks:
      - shared-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ compute, utility ]

  comfyui-dev2: &automatic
    <<: *base_service
    profiles: [ "comfyui-dev2" ]
    container_name: comfyui-dev2
    ports:
      - "${WEBUI_PORT:-62805}:7860"
    volumes:
      - &v1 ./volumes/comfyui-dev/data:/data
      - &v2 ./volumes/comfyui-dev/output:/output
      - &v3 ./volumes:/volumes
      - &v4 ./volumes/comfyui-dev/data/extra_model_paths.yaml:/home/aigc/app/extra_model_paths.yaml

    environment:
      - CLI_ARGS=--port 7860 --disable-cuda-malloc
    networks:
      - shared-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '3' ]
              capabilities: [ compute, utility ]

  comfyui: &automatic
    <<: *base_service
    profiles: [ "comfyui" ]
    container_name: comfyui
    ports:
      - "${WEBUI_PORT:-62799}:7860"
    volumes:
      - &v1 ./volumes/comfyui/data:/data
      - &v2 /tmp/output111:/output
      - &v3 ./volumes:/volumes
      - &v4 ./volumes/comfyui/data/extra_model_paths.yaml:/home/aigc/app/extra_model_paths.yaml

    environment:
      - CLI_ARGS=--port 7860 --disable-cuda-malloc
    networks:
      - shared-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ compute, utility ]

networks:
  shared-network:
    external: true # 使用外部已经存在的网络
