x-base_service: &base_service
  build: ./services/comfy/
  image: fmsunyh/sd-comfy:latest

  stop_signal: SIGKILL
  tty: true
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: [ '0' ]
            capabilities: [ compute, utility ]
  extra_hosts:
    - "raw.githubusercontent.com:185.199.108.133"
  user: "aigc:aigc" # 容器进程以 aigc 用户身份运行

name: comfyui

services:
  flux: &automatic
    <<: *base_service
    profiles: [ "flux" ]
    container_name: comfyui-flux
    ports:
      - "${WEBUI_PORT:-62799}:7860"
    volumes:
      - &v1 ./volumes/flux/data:/data
      - &v2 ./volumes/flux/output:/output

    environment:
      - CLI_ARGS=--port 7860 --disable-cuda-malloc
    networks:
      - shared-network

  comfyui: &automatic
    <<: *base_service
    profiles: [ "comfyui" ]
    container_name: comfyui
    ports:
      - "${WEBUI_PORT:-62799}:7860"
    volumes:
      - &v1 ./volumes/comfyui/data:/data
      - &v2 ./volumes/comfyui/output:/output

    environment:
      - CLI_ARGS=--port 7860 --disable-cuda-malloc
    networks:
      - shared-network

networks:
  shared-network:
    external: true # 使用外部已经存在的网络
